version: '3'

services:
  algod:
    image: makerxau/algorand-sandbox-dev:latest
    container_name: algod
    ports:
      - 4001:4001
      - 4002:4002
      - 9392:9392

  indexer:
    image: makerxau/algorand-indexer-dev:latest
    container_name: algo-indexer
    ports:
      - 8980:8980
    restart: unless-stopped
    environment:
      ALGOD_HOST: algod
      POSTGRES_HOST: indexer-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer_db
    depends_on:
      - indexer-db
      - algod

  indexer-db:
    image: postgres:13-alpine
    container_name: algo-pg
    ports:
      - 5433:5432
    user: postgres
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer_db
